import SideBar from "@/components/SideBar";
import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="darks">
      <body className="dark:bg-body bg-white font-[Sora] dark:text-white text-dark">
        <Header />
        <main>
          <div className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
            <SideBar />
            {children}
            <div id="modal-root-content" />
          </div>
        </main>
      </body>
    </html>
  );
}
